### ISSUE TITLE
pip's dependency conflict: accelerate

### ISSUE THREAD

**Issue by liwd190019** [RLHFlow/Online-RLHF#19]
Thank authors for this awesome repo!
I think I strictly follow the training environment procedure in the readme. But I got this error while `pip install accelerate==0.27.2`
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
alignment-handbook 0.4.0.dev0 requires accelerate==0.23.0, but you have accelerate 0.27.2 which is incompatible.
```
Is it an critical issue for the training?

**Comment by WayXG** [comment]
I do not think so. I have tried the repo for my personal research with Mistral and llama3 and it works pretty nice and leads to SOTA performance. 

Though one problem is that it does not support Gemma 2 currently
