### ISSUE TITLE
Question about the iteration dataset (information leakage)?

### ISSUE THREAD

**Issue by hhhhzzzzz** [RLHFlow/Online-RLHF#21]
Hi,

In the RLHFlow/iterative-prompt-v1-iter1-20K dataset, I've noticed that the 'context_messages' include entries labeled as 'assistant.' However, in the hendrydong/preference_700K dataset, the context labeled as 'user' is the prompt, and the context labeled as 'assistant' is the response.

This raises the question: Does the RLHFlow/iterative-prompt-v1-iter1-20K dataset include responses given the prompt? If so, could this be considered information leakage within the dataset? In my opinion, the RLHFlow/iterative-prompt-v1-iter1-20K dataset should only include the prompts, not the responses.

![WechatIMG1248](https://github.com/user-attachments/assets/28a6cd1f-70cb-451e-92d4-16a925f8398b)

**Comment by WeiXiongUST** [comment]
Hi, I think this is because some of the prompt are **multi-turn**, which means that it consists of a conversation history instead of a single instruction. For instance, many of the prompts from HH-RLHF are multi-turn.

**Comment by WeiXiongUST** [comment]
Handling multi-turn chat is more complicated. If you only want to work with single-turn chat, you can try the ultra feedback prompt in : weqweasdas/ultra_prompt_split

**Comment by WeiXiongUST** [comment]
> Hi @WeiXiongUST , can you suggest some repositories or instructions that hint us how to handle multi-turn chat?

The reward modeling present in the RLHF Workflow can handle multi-turn chat because we include the HH-RLHF in the training data. The DPO and PPO also naturally handle the multi-turn chat by using the multi-turn conversation history as a prompt. 

To learn multi-turn in the response part, we need new algorithms. I have a paper on this topic but is still under the internal review of google...

**Comment by hhhhzzzzz** [comment]
> Hi, I think this is because some of the prompt are **multi-turn**, which means that it consists of a conversation history instead of a single instruction. For instance, many of the prompts from HH-RLHF are multi-turn.

the context_messages[:-1] can be regarded as prompt? and context_messages[-1] can be regarded as response?

**Comment by WeiXiongUST** [comment]
> > Hi, I think this is because some of the prompt are **multi-turn**, which means that it consists of a conversation history instead of a single instruction. For instance, many of the prompts from HH-RLHF are multi-turn.
> 
> so in the hendrydong/preference_700K dataset, the choosen[:-1] (or rejected[:-1]) can be regarded as prompt? and choosen[-1] can be regarded as response?

Yes, you are correct!

**Comment by hhhhzzzzz** [comment]
> > > Hi, I think this is because some of the prompt are **multi-turn**, which means that it consists of a conversation history instead of a single instruction. For instance, many of the prompts from HH-RLHF are multi-turn.
> > 
> > 
> > so in the hendrydong/preference_700K dataset, the choosen[:-1] (or rejected[:-1]) can be regarded as prompt? and choosen[-1] can be regarded as response?
> 
> Yes, you are correct!

Thanks a lot for your reply! Thanks!

**Comment by hhhhzzzzz** [comment]
Hi,

Could you tell me how to select prompts to form the iterative dataset?
